name: daest
channels: [pytorch, nvidia, conda-forge, defaults]
dependencies:
  - python=3.11
  - pytorch
  - pytorch-cuda
  - numpy
  - pandas
  - scipy
  - matplotlib
  - hdf5storage
  - tqdm
  - pip
  - pip:
      - pytorch-lightning
      - hydra-core
      - omegaconf
      - mne
